name: Deploy

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: "${{ secrets.DH_REGISTRY_USER }}/simple-telegram-bot"
        
jobs:
  build-job:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.meta.outputs.tag }}
    
    steps:
      - uses: actions/checkout@v5
      
      - name: set image tag
        id: meta
        run: echo "tag=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
        
      - name: login to docker hub
        run: |
          echo "${{ secrets.DH_REGISTRY_PASSWORD }}" | \
          docker login -u "${{ secrets.DH_REGISTRY_USER }}" --password-stdin 
        
      - name: build & push
        run: |
          docker build -t $IMAGE_NAME:${{ steps.meta.outputs.tag }} .
          docker push $IMAGE_NAME:${{ steps.meta.outputs.tag }}
          docker tag $IMAGE_NAME:${{ steps.meta.outputs.tag }} $IMAGE_NAME:latest
          docker push $IMAGE_NAME:latest
      
  deploy-job:
    runs-on: ubuntu-latest
    needs: build-job
    
    steps:
      - uses: actions/checkout@v5
      - name: setup ssh
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          
      - name: install Ansible
        run: sudo apt-get update && sudo apt-get install -y ansible
        
      - name: deploy with Ansible
        run: |
          ansible-playbook ansible/playbooks/deploy.yml \
            -i ansible/inventory/prod.ini \
            --extra-vars "image_tag=${{ needs.build.outputs.image_tag }}"